set dotenv-load
set positional-arguments

rustflags := "-C target-feature=+crt-static"
rust_target := "x86_64-unknown-linux-musl"

default:
    @just --list

build:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo build \
        --release \
        --target '{{ rust_target }}'

dev-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
          just dev-run "$@"

dev-run *args: migrations-run
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target "{{ rust_target }}" \
        -- {{ args }} \

watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just run "$@"

run *args:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo run \
        --target '{{ rust_target }}' \
        --release \
        -- "$@" \

test *args:
    SQLX_OFFLINE=true \
    RUSTFLAGS='{{ rustflags }}' \
    cargo test \
        --target '{{ rust_target }}' \
        --workspace \
        --all-features \
        -- "$@" \

test-watch *args:
    RUSTFLAGS='{{ rustflags }}' \
    watchexec \
        --clear=reset \
        --restart \
        --debounce '500ms' \
        --stop-signal 'kill' \
        -- \
            just test "$@"

fmt-dev: lint-fix && fmt
    rustup run nightly cargo fmt --all \

lint:
    SQLX_OFFLINE=true \
    cargo clippy \
        --workspace \
        --all-features \
        -- \

lint-fix:
    SQLX_OFFLINE=true \
    cargo clippy \
        --fix \
        --allow-dirty \
        --allow-staged \
        --workspace \
        --all-features \
        -- \

fmt:
    cargo fmt --all 2>/dev/null \

sqlx-regenerate:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -z "$DATABASE_URL" ]; then
      echo "DATABASE_URL must be set to a postgres:// URL"; exit 1;
    fi
    export SQLX_OFFLINE=""
    sqlx database drop -y
    sqlx database create
    sqlx migrate run
    cargo sqlx prepare --workspace

migrations-run:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ -z "$DATABASE_URL" ]; then
      echo "DATABASE_URL is not set"; exit 1;
    fi
    sqlx migrate run

migrations-list:
    sqlx migrate info

migrations-add $name="":
    name="{{ name }}"; \
    if [ -z "$name" ]; then \
        read -p "Enter migration name: " name; \
    fi; \
    sqlx migrate add -r "$name" \

dev-db:
    docker run \
      --name zet-live-pg \
      -e POSTGRES_USER=zet_live \
      -e POSTGRES_PASSWORD=zet_live \
      -e POSTGRES_DB=zet_live \
      -p 127.0.0.1:5436:5432 \
      postgres:18 \
    ;
